# Generated by Django 5.2 on 2025-04-27 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('menu_name', models.CharField(max_length=100, verbose_name='категория меню')),
                ('url', models.CharField(blank=True, max_length=200, verbose_name='путь')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tree_menu.menuitem', verbose_name='родитель')),
            ],
            options={
                'verbose_name': 'Меню',
                'verbose_name_plural': 'элементы меню',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['menu_name'], name='tree_menu_m_menu_na_036b21_idx'), models.Index(fields=['parent'], name='tree_menu_m_parent__f5fc6a_idx')],
            },
        ),
    ]
