# Generated by Django 5.2 on 2025-04-27 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tree_menu', '0003_alter_menuitem_named_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='named_url',
        ),
    ]
